- name: My first play
  hosts: Docker
  become: true
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
   - name: get SUDO rights
     command: sudo -l
     become: true
     become_user: root
