---
- name: Update all packages to their latest version
  hosts: dockerdmz
  become: true
  become_method: su
  tasks:
  - name: First Task update dmz servers
    ansible.builtin.apt:
      name: "*"
      state: latest
  - name: second task
    ansible.builtin.reboot:
    
